services:
  - type: web
    name: task-manager-api
    env: node
    rootDir: task-api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
