services:
  - type: web
    name: task-manager-api
    env: node
    buildCommand: cd task-api && npm install
    startCommand: cd task-api && npm start
    envVars:
      - key: PORT
        value: 3000
